Add GSL 2.6
dealii/candi pull request #178
Opened 2021-05-25 17:55 UTC by gfcas

Same as #177. This adds the GSL 2.6 release. Testes locally on WSL Ubuntu 20.04.

2021-05-26 11:25 UTC, koecher requested changes
Better approach suggested.

2021-05-26 11:25 UTC, koecher commented on deal.II-toolchain/packages/gsl.package
> +package_specific_build () {
As far as I can see, we can use
`package_specific_setup () { ./autogen.sh }` and set
`CONFOPTS="--enable-maintainer-mode"`

I check that and write you.

2021-05-26 11:25 UTC, koecher commented
I'll send you an email with my suggested approach. Please check this for you environment and update

2021-05-26 11:33 UTC, gfcas commented on deal.II-toolchain/packages/gsl.package
> +
Ups, I adopted it from the clang-format for dealii. But no problem.

2021-05-26 12:10 UTC, gfcas commented
> 
> 
> I'll send you an email with my suggested approach. Please check this for you environment and update

@koecher thanks! Updated version is pushed.

2021-05-26 12:14 UTC, gfcas commented
Maybe the CI test is not really meaningful in its current state, since the changes are not used. Should I activate the gsl package in the default candi.cfg file?

2021-05-27 08:45 UTC, koecher approved these changes

2021-05-27 08:47 UTC, merged