new global option: USE_64_BIT_INDICES
dealii/candi pull request #295
Opened 2022-05-15 15:57 UTC by tjhei

2022-05-16 19:44 UTC, koecher commented
looks nice. Are there more packages like slepc or p4est which needs this information as well? (A question to the experts). 

Otherwise, just merge.

2022-05-17 20:21 UTC, koecher requested changes

2022-05-17 20:24 UTC, koecher commented
@tjhei, in this setting, I believe that slepc is using the best fit "confopts" from petsc, but this is not the way we should go for candi...

2022-05-17 20:26 UTC, tjhei commented on deal.II-toolchain/packages/slepc.package
> +    ${PYTHON_INTERPRETER} ./configure --prefix=${INSTALL_PATH}
No, CONFOPTS is empty and you do not (can not) specify Petsc options here. Slepc grabs them from Petsc automatically. I don't think there is a different way to do this.

2022-05-17 20:33 UTC, koecher commented on deal.II-toolchain/packages/slepc.package
> +    ${PYTHON_INTERPRETER} ./configure --prefix=${INSTALL_PATH}
ah, snap - those were different files - sorry. Maybe we haven't reset CONFOPTS correctly, or there is something in the defaults which now breaks slepc, if this line is the deal-breaker.

2022-05-17 20:34 UTC, koecher commented on deal.II-toolchain/packages/slepc.package
> +    ${PYTHON_INTERPRETER} ./configure --prefix=${INSTALL_PATH}
anyhow, we should make it possible, that CONFOPTS is still pushed to the configure of slepc as well

2022-06-04 02:43 UTC, tjhei commented
I think you misunderstood: I deleted ``${CONFOPTS}`` because it is an unused/empty variable. SLEPc does not need PETSc arguments but grabs them from the PETSc installation. It is in fact an error to provide PETSc options here.

CONFOPTS is reset in candi.sh here: https://github.com/dealii/candi/blob/609ef27b96f92dc402ce59b1d4509f23a676cc89/candi.sh#L1107

2022-06-16 22:42 UTC, tjhei commented
I am fairly confident that this is correct, so I am merging.

2022-06-16 22:42 UTC, merged